replicaCount: 1

image:
  repository: tusharthapliyal/flask-api:2
  pullPolicy: Always

user: 1000

service:
  type: NodePort
  port: 80
  targetPort: 5000
  nodePort: 30000 

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

volumes:
 - name: mypv
   persistentVolumeClaim:
     claimName: mypvc

volumeMounts:
 - name: mypv
   mountPath: "/home/tushar/app/app-data"
   hostPath: "/home/ubuntu/project/flask-api"
   readOnly: false
