apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-api
  namespace: tushar
spec:
  selector:
    matchLabels:
      app: flask-api
  template:
    metadata:
      labels:
        app: flask-api
    spec:

      initContainers:
      - name: fix-permissions
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 {{ (index .Values.volumeMounts 0).mountPath }}"]
        volumeMounts:
          - name: mypv
            mountPath: {{ (index .Values.volumeMounts 0).mountPath }}
      
      containers:
      - name: flask-api
        image: {{ .Values.image.repository }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
          - mountPath: {{ (index .Values.volumeMounts 0).mountPath }}
            name: mypv
        securityContext:
          runAsUser: {{ .Values.user }}
        resources:
          limits:
            memory: {{ .Values.resources.limits.memory }}
            cpu: {{ .Values.resources.limits.cpu }}
          requests:
            memory: {{ .Values.resources.requests.memory }}
            cpu: {{ .Values.resources.requests.cpu }}
        ports:
        - containerPort: 5000
        envFrom:
          - configMapRef:
              name: flask-api-cm
          - secretRef:
              name: flask-api-sec
      volumes:
        - name: {{ (index .Values.volumeMounts 0).name }}
          persistentVolumeClaim:
            claimName: {{ (index .Values.volumes 0).persistentVolumeClaim.claimName }}



