apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ (index .Values.volumeMounts 0).name }}
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ (index .Values.volumeMounts 0).hostPath }}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ (index .Values.volumes 0).persistentVolumeClaim.claimName }}
  namespace: tushar
spec:
  resources:
    requests:
      storage: 2Gi
  accessModes:
    - ReadWriteOnce

