apiVersion: v1
kind: Service
metadata:
  name: flask-api-nodeport
  namespace: tushar
spec:
  type: NodePort
  selector:
    app: flask-api
  ports:
  - port: 80
    targetPort: 5000 
    nodePort: 30000 
